// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw3lgjDec-00blNtnqWFRFyO-YsFMcTmw',
    appId: '1:787808939071:web:e9dd8f1d2cede748d5dc8a',
    messagingSenderId: '787808939071',
    projectId: 'dasapp-2767c',
    authDomain: 'dasapp-2767c.firebaseapp.com',
    databaseURL: 'https://dasapp-2767c.firebaseio.com',
    storageBucket: 'dasapp-2767c.appspot.com',
    measurementId: 'G-HNJ3MR681W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA65v2QubAw2pfaJhMcPE3OI5L-wRVZuFw',
    appId: '1:787808939071:android:111572a62a60cf72d5dc8a',
    messagingSenderId: '787808939071',
    projectId: 'dasapp-2767c',
    databaseURL: 'https://dasapp-2767c.firebaseio.com',
    storageBucket: 'dasapp-2767c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCAaIMIoIA0D11YwH4AtO80DzFkHM2vaI',
    appId: '1:787808939071:ios:76a25c3211f0ce5dd5dc8a',
    messagingSenderId: '787808939071',
    projectId: 'dasapp-2767c',
    databaseURL: 'https://dasapp-2767c.firebaseio.com',
    storageBucket: 'dasapp-2767c.appspot.com',
    iosBundleId: 'com.example.restaurentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCAaIMIoIA0D11YwH4AtO80DzFkHM2vaI',
    appId: '1:787808939071:ios:3efae3fc85fbc3cad5dc8a',
    messagingSenderId: '787808939071',
    projectId: 'dasapp-2767c',
    databaseURL: 'https://dasapp-2767c.firebaseio.com',
    storageBucket: 'dasapp-2767c.appspot.com',
    iosBundleId: 'com.example.restaurentApp.RunnerTests',
  );
}
